spring:
  application:
    name: springDemo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789
    jpa:
      hibernate:
        ddl-auto: none

      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true